name: Docker Image

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'flake.*'
      - 'Cargo.*'
      - 'assets/**/*'
      - 'src/**/*'
      - 'public/purify.min.js'

    branches:
      - main

jobs:
  deploy:
    name: Build & push image
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v15

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            /nix/store/
          key: ${{ runner.os }}-${{ hashFiles('flake.lock')}}-${{ hashFiles('Cargo.lock')}}

      - name: Build image
        run: |
          nix build .#emojied-docker
          docker load < result

      - name: Rename image
        run: docker tag emojied-docker:latest hsekun/emojied:latest

      - name: Push image
        run: docker push hsekun/emojied:latest


